version: '2'

services:
  mongo:
    image: mongo:4.4.6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      exchange_network:
        ipv4_address: 10.6.0.2

  redis:
    container_name: cdr_cache
    image: redis:6.2.6
    ports:
      - "6379:6379"
    networks:
      exchange_network:
        ipv4_address: 10.6.0.3

  app:
    container_name: cdr_app
    restart: on-failure
    build:
      context: ./
      dockerfile: dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://10.6.0.2:27017/cdr
      - SPRING_DATA_MONGODB_DATABASE=cdr
      - SPRING_REDIS_HOST=10.6.0.3
      - SPRING_REDIS_PORT=6379
    depends_on:
      - mongo
      - redis
    networks:
      exchange_network:
        ipv4_address: 10.6.0.4

networks:
  exchange_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16

volumes:
  mongo-data:
